import compilers.diagnostics.Diagnostic;
import compilers.diagnostics.DiagnosticReporter;
import compilers.flask.SymbolTable.SymbolTableBuilder;
import compilers.flask.antlr_gen.FlaskLexer;
import compilers.flask.antlr_gen.FlaskParser;
import compilers.flask.ast.builder.ASTBuilder;
import compilers.flask.ast.nodes.ASTNode;
import compilers.flask.ast.nodes.statements.ProgramNode;
import compilers.flask.codegen.FlaskBytecodeCompiler;
import compilers.flask.codegen.GenerationResult;
import compilers.flask.codegen.analysis.BindingAnalysisResult;
import compilers.flask.codegen.analysis.BindingResolver;
import compilers.flask.semantic.SemanticAnalyzer;
import compilers.flask.semantic.validation.AstStructuralValidator;
import compilers.flask.semantic.validation.ScopeRuleChecker;
import compilers.flask.vm.BytecodeVM;
import compilers.flask.vm.ExecutionLimits;
import compilers.flask.vm.Namespace;
import compilers.flask.vm.VmResult;
import compilers.flask.vm.VmCapabilities;
import compilers.flask.vm.modules.ModuleRegistry;
import compilers.flask.vm.flask.PyFlaskApp;
import compilers.flask.vm.flask.PyRequest;
import compilers.flask.vm.flask.PyTemplateRenderRequest;
import compilers.flask.vm.values.PyBool;
import compilers.flask.vm.values.PyDict;
import compilers.flask.vm.values.PyInt;
import compilers.flask.vm.values.PyList;
import compilers.flask.vm.values.PyString;
import compilers.flask.vm.values.PyValue;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;

import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.Collections;
import java.util.Map;

/** End-to-end acceptance matrix for Part-3 functions, classes, and imports. */
public final class FlaskPart3EndToEndHarness {
    private static int passed;
    private static int failed;

    private FlaskPart3EndToEndHarness() { }

    public static void main(String[] args) {
        run("functions, defaults, keywords, recursion, and closures",
                FlaskPart3EndToEndHarness::testFunctions);
        run("decorator definition/apply order and native list method",
                FlaskPart3EndToEndHarness::testDecorator);
        run("classes, inherited init, bound override, and attributes",
                FlaskPart3EndToEndHarness::testClasses);
        run("class body carries lexical free variables into methods",
                FlaskPart3EndToEndHarness::testClassClosure);
        run("native object/Exception bases integrate with generated mixed C3",
                FlaskPart3EndToEndHarness::testNativeBaseClasses);
        run("native import/from/star and dotted result modes",
                FlaskPart3EndToEndHarness::testImports);
        run("nested runtime failure produces full source traceback",
                FlaskPart3EndToEndHarness::testTraceback);
        run("default builtins and Flask route bridge execute end to end",
                FlaskPart3EndToEndHarness::testFlaskBridge);
        run("builtin range/container methods execute through generated bytecode",
                FlaskPart3EndToEndHarness::testBuiltinExecution);
        run("fixture os import and rooted os.path capability execute end to end",
                FlaskPart3EndToEndHarness::testOsCapability);

        if (failed != 0) {
            throw new AssertionError(failed + " Part-3 E2E test(s) failed; "
                    + passed + " passed");
        }
        System.out.println("All " + passed + " Part-3 E2E tests passed.");
    }

    private static void testFunctions() {
        VmResult result = execute(lines(
                "def add(a, b=2):",
                "    return a + b",
                "def factorial(n):",
                "    if n <= 1:",
                "        return 1",
                "    return n * factorial(n - 1)",
                "def outer(seed):",
                "    box = [seed]",
                "    def read(delta=0):",
                "        return box[0] + delta",
                "    return read",
                "def first(values):",
                "    for value in values:",
                "        return value",
                "    return 0",
                "fn = outer(10)",
                "a = add(3)",
                "b = add(b=5, a=4)",
                "c = factorial(6)",
                "d = fn()",
                "e = fn(7)",
                "f = first([88, 99])"), ModuleRegistry.empty());
        success(result);
        integer(result, "a", 5);
        integer(result, "b", 9);
        integer(result, "c", 720);
        integer(result, "d", 10);
        integer(result, "e", 17);
        integer(result, "f", 88);
    }

    private static void testDecorator() {
        VmResult result = execute(lines(
                "events = []",
                "def decorate(fn):",
                "    events.append('applied')",
                "    return fn",
                "@decorate",
                "def answer():",
                "    return 42",
                "@decorate",
                "class Tagged:",
                "    marker = 9",
                "value = answer()",
                "tag = Tagged.marker"), ModuleRegistry.empty());
        success(result);
        integer(result, "value", 42);
        PyValue events = result.getGlobals().get("events");
        check(events instanceof PyList, "events is not a list");
        equal(Arrays.asList(new PyString("applied"), new PyString("applied")),
                ((PyList) events).getElements(), "decorator application order");
        integer(result, "tag", 9);
    }

    private static void testClasses() {
        VmResult result = execute(lines(
                "class Base:",
                "    def __init__(self, value):",
                "        self.value = value",
                "    def get(self):",
                "        return self.value",
                "class Child(Base):",
                "    marker = 8",
                "    def get(self):",
                "        return self.value + 1",
                "obj = Child(4)",
                "before = obj.get()",
                "obj.value = 20",
                "after = obj.get()",
                "class_value = Child.marker"), ModuleRegistry.empty());
        success(result);
        integer(result, "before", 5);
        integer(result, "after", 21);
        integer(result, "class_value", 8);
    }

    private static void testClassClosure() {
        VmResult result = execute(lines(
                "def make(value):",
                "    class Holder:",
                "        def read(self):",
                "            return value",
                "    return Holder",
                "Holder = make(33)",
                "instance = Holder()",
                "captured = instance.read()"), ModuleRegistry.empty());
        success(result);
        integer(result, "captured", 33);
    }

    private static void testNativeBaseClasses() {
        GenerationResult generation = compile(lines(
                "class Plain(object):",
                "    marker = 5",
                "    def read(self):",
                "        return self.marker",
                "plain = Plain()",
                "plain_value = plain.read()",
                "plain_is_object = isinstance(plain, object)",
                "plain_sub_object = issubclass(Plain, object)",
                "class LeftError(Exception):",
                "    side = 'left'",
                "class RightError(Exception):",
                "    side = 'right'",
                "class MixedError(LeftError, RightError):",
                "    pass",
                "mixed = MixedError()",
                "mixed_side = mixed.side",
                "mixed_is_exception = isinstance(mixed, Exception)",
                "mixed_is_base = isinstance(mixed, BaseException)",
                "mixed_sub_exception = issubclass(MixedError, Exception)",
                "mixed_mro = MixedError.__mro__",
                "mro_left = mixed_mro[1].__name__",
                "mro_right = mixed_mro[2].__name__"));
        check(generation.isSuccess(),
                "native-base fixture failed:\n" + diagnostics(generation));
        VmResult result = new BytecodeVM().execute(generation.requireModule());
        success(result);
        integer(result, "plain_value", 5);
        equal(PyBool.TRUE, result.getGlobals().get("plain_is_object"),
                "isinstance plain/object");
        equal(PyBool.TRUE, result.getGlobals().get("plain_sub_object"),
                "issubclass Plain/object");
        equal(new PyString("left"), result.getGlobals().get("mixed_side"),
                "mixed MRO attribute precedence");
        equal(PyBool.TRUE, result.getGlobals().get("mixed_is_exception"),
                "isinstance mixed/Exception");
        equal(PyBool.TRUE, result.getGlobals().get("mixed_is_base"),
                "isinstance mixed/BaseException");
        equal(PyBool.TRUE, result.getGlobals().get("mixed_sub_exception"),
                "issubclass mixed/Exception");
        equal(new PyString("LeftError"), result.getGlobals().get("mro_left"),
                "mixed C3 first user base");
        equal(new PyString("RightError"), result.getGlobals().get("mro_right"),
                "mixed C3 second user base");
    }

    private static void testImports() {
        ModuleRegistry registry = ModuleRegistry.builder()
                .registerNative("demo", (module, loader) -> {
                    module.put("value", PyInt.valueOf(9));
                    module.put("public", new PyString("yes"));
                    module.put("_hidden", PyInt.ZERO);
                })
                .registerNativePackage("pkg")
                .registerNative("pkg.child", (module, loader) ->
                        module.put("value", PyInt.valueOf(12)))
                .build();
        VmResult result = execute(lines(
                "import demo",
                "from demo import value as imported",
                "from demo import *",
                "import pkg.child",
                "import pkg.child as leaf",
                "a = demo.value",
                "b = imported",
                "c = public",
                "d = pkg.child.value",
                "e = leaf.value"), registry);
        success(result);
        integer(result, "a", 9);
        integer(result, "b", 9);
        equal(new PyString("yes"), result.getGlobals().get("c"), "star import");
        integer(result, "d", 12);
        integer(result, "e", 12);
        check(!result.getGlobals().containsKey("_hidden"),
                "star import leaked underscore name");
    }

    private static void testTraceback() {
        VmResult result = execute(lines(
                "def inner(value):",
                "    return 1 / value",
                "def outer():",
                "    return inner(0)",
                "answer = outer()"), ModuleRegistry.empty());
        check(result.isFailure(), "division by zero unexpectedly succeeded");
        equal("ZeroDivisionError",
                result.getTraceback().getException().getExceptionTypeName(),
                "traceback exception type");
        equal(3, result.getTraceback().getEntries().size(), "traceback frame count");
        check(result.getTraceback().getEntries().get(2).getCodeName().endsWith("inner"),
                "traceback omitted inner frame");
        check(result.getTraceback().getEntries().get(1).getCodeName().endsWith("outer"),
                "traceback omitted outer frame");
    }

    private static void testFlaskBridge() {
        GenerationResult generation = compile(lines(
                "import os",
                "from flask import Flask, request, session, render_template",
                "app = Flask(__name__)",
                "@app.route('/hello', methods=['GET'])",
                "def hello():",
                "    session['visited'] = 1",
                "    print('route', request.method)",
                "    return render_template('hello.html', method=request.method)"));
        check(generation.isSuccess(), "Flask fixture failed:\n" + diagnostics(generation));
        BytecodeVM vm = new BytecodeVM();
        VmResult module = vm.execute(generation.requireModule());
        success(module);
        check(module.getGlobals().get("app") instanceof PyFlaskApp,
                "Flask constructor did not create an app");
        PyDict session = new PyDict();
        VmResult route = vm.invokeRoute(
                (PyFlaskApp) module.getGlobals().get("app"),
                "hello", new PyRequest("GET", "/hello"), session);
        success(route);
        check(route.getReturnValue() instanceof PyTemplateRenderRequest,
                "render_template did not preserve the template boundary value");
        equal(PyInt.ONE, session.find(new PyString("visited")).orElse(null),
                "route session mutation");
        equal("route GET\n", route.getStdout(), "captured route print output");
    }

    private static void testBuiltinExecution() {
        GenerationResult generation = compile(lines(
                "values = []",
                "for item in range(4):",
                "    values.append(item)",
                "count = len(values)",
                "total = sum(values)",
                "text = str(total)",
                "print(text)"));
        check(generation.isSuccess(), "builtin fixture failed:\n" + diagnostics(generation));
        VmResult result = new BytecodeVM().execute(generation.requireModule());
        success(result);
        integer(result, "count", 4);
        integer(result, "total", 6);
        equal(new PyString("6"), result.getGlobals().get("text"), "str builtin");
        equal("6\n", result.getStdout(), "print capture");

        GenerationResult fileGeneration = compile(lines(
                "handle = open('fixture.txt')",
                "content = handle.read()",
                "joined = ''",
                "for line in handle:",
                "    joined += line"));
        check(fileGeneration.isSuccess(), "open fixture failed to compile");
        VmResult fileResult = new BytecodeVM(
                ExecutionLimits.DEFAULT,
                VmCapabilities.withFileSystemRead(path -> {
                    equal("fixture.txt", path, "capability path");
                    return "sandboxed\ntext";
                })).execute(fileGeneration.requireModule());
        success(fileResult);
        equal(new PyString("sandboxed\ntext"), fileResult.getGlobals().get("content"),
                "capability-backed open/read");
        equal(new PyString("sandboxed\ntext"), fileResult.getGlobals().get("joined"),
                "capability-backed file iteration");
    }

    private static void testOsCapability() throws Exception {
        Path root = Files.createTempDirectory(
                java.nio.file.Paths.get(".tmp"), "flask-vm-os-");
        Path present = root.resolve("present.txt");
        Files.write(present, Collections.singletonList("present"),
                StandardCharsets.UTF_8);
        try {
            GenerationResult generation = compile(lines(
                    "import os",
                    "joined = os.path.join('uploads', 'avatar.png')",
                    "present = os.path.exists('present.txt')"));
            check(generation.isSuccess(), "os fixture failed:\n" + diagnostics(generation));
            VmResult result = new BytecodeVM(
                    ExecutionLimits.DEFAULT,
                    VmCapabilities.rootedFileSystemRead(root))
                    .execute(generation.requireModule());
            success(result);
            equal(new PyString("uploads/avatar.png"), result.getGlobals().get("joined"),
                    "deterministic os.path.join");
            equal(compilers.flask.vm.values.PyBool.TRUE,
                    result.getGlobals().get("present"), "rooted os.path.exists");

            GenerationResult escape = compile(lines(
                    "import os",
                    "outside = os.path.exists('../outside.txt')"));
            VmResult denied = new BytecodeVM(
                    ExecutionLimits.DEFAULT,
                    VmCapabilities.rootedFileSystemRead(root))
                    .execute(escape.requireModule());
            check(denied.isFailure(), "os.path traversal unexpectedly succeeded");
            equal("PermissionError",
                    denied.getTraceback().getException().getExceptionTypeName(),
                    "rooted os.path traversal error");
        } finally {
            Files.deleteIfExists(present);
            Files.deleteIfExists(root);
        }
    }

    private static VmResult execute(String source, ModuleRegistry registry) {
        GenerationResult generation = compile(source);
        if (!generation.isSuccess()) {
            throw new AssertionError("compilation failed:\n" + diagnostics(generation));
        }
        return new BytecodeVM(
                ExecutionLimits.DEFAULT, new Namespace(), registry)
                .execute(generation.requireModule());
    }

    private static GenerationResult compile(String source) {
        FlaskLexer lexer = new FlaskLexer(CharStreams.fromString(source));
        CommonTokenStream tokens = new CommonTokenStream(lexer);
        FlaskParser parser = new FlaskParser(tokens);
        FlaskParser.ProgramContext tree = parser.program();
        check(parser.getNumberOfSyntaxErrors() == 0, "parser rejected fixture");
        ASTNode root = new ASTBuilder("part3_fixture.py").visit(tree);
        check(root instanceof ProgramNode, "AST root is not ProgramNode");
        ProgramNode program = (ProgramNode) root;

        DiagnosticReporter reporter = new DiagnosticReporter();
        if (!new AstStructuralValidator(reporter, "part3_fixture.py").validate(program)) {
            return GenerationResult.failure(reporter);
        }
        SymbolTableBuilder symbols = new SymbolTableBuilder(reporter, "part3_fixture.py");
        program.accept(symbols);
        new ScopeRuleChecker(symbols.getSymbolTable(), reporter, "part3_fixture.py")
                .check(program);
        new SemanticAnalyzer(symbols.getSymbolTable(), "part3_fixture.py", reporter)
                .analyze(program);
        if (reporter.hasErrors()) return GenerationResult.failure(reporter);
        BindingAnalysisResult bindings = new BindingResolver().resolve(program);
        return new FlaskBytecodeCompiler().compile(
                program, bindings, "part3_fixture.py", "part3_fixture", reporter);
    }

    private static String diagnostics(GenerationResult result) {
        StringBuilder text = new StringBuilder();
        for (Diagnostic diagnostic : result.getReporter().diagnostics()) {
            text.append(diagnostic).append('\n');
        }
        return text.toString();
    }

    private static void success(VmResult result) {
        if (result.isFailure()) {
            throw new AssertionError(result.getTraceback().format());
        }
    }

    private static void integer(VmResult result, String name, long expected) {
        PyValue value = result.getGlobals().get(name);
        check(value instanceof PyInt, name + " is not int: " + value);
        equal(BigInteger.valueOf(expected), ((PyInt) value).getValue(), name);
    }

    private static String lines(String... lines) {
        return String.join("\n", lines) + "\n";
    }

    private static void run(String name, Checked test) {
        try {
            test.run();
            passed++;
            System.out.println("PASS  " + name);
        } catch (Throwable failure) {
            failed++;
            System.err.println("FAIL  " + name + " -> " + failure);
            failure.printStackTrace(System.err);
        }
    }

    private static void check(boolean condition, String message) {
        if (!condition) throw new AssertionError(message);
    }

    private static void equal(Object expected, Object actual, String label) {
        if (expected == null ? actual != null : !expected.equals(actual)) {
            throw new AssertionError(label + ": expected <" + expected
                    + "> but got <" + actual + ">");
        }
    }

    @FunctionalInterface private interface Checked { void run() throws Exception; }
}
